export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOAD_USER = "LOAD_USER";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const HEADER_COLOR = "HEADER_COLOR";
export const SIDEBAR_COLOR = "SIDEBAR_COLOR";
export const OPEN_NOTIFICATION = "OPEN_NOTIFICATION";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";
